spring.application.name=servicio-pedidos
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gb_pedidos?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true