spring.application.name=servicio-pedidos

# Puerto diferente para pedidos
server.port=8082

# --- CONFIGURACIÓN PARA MYSQL (XAMPP) ---
spring.datasource.url=jdbc:mysql://localhost:3306/gamebakes_pedidos?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true