CREATE DATABASE IF NOT EXISTS gb_usuarios;
CREATE DATABASE IF NOT EXISTS gb_resenas;
CREATE DATABASE IF NOT EXISTS gb_pedidos;
CREATE DATABASE IF NOT EXISTS gb_perfil;
CREATE DATABASE IF NOT EXISTS gb_productos;
CREATE DATABASE IF NOT EXISTS gb_pagos;