spring.application.name=servicio-resenas

# Puerto donde correrá este microservicio (8081 para no chocar con el Front)
server.port=8081

# Configuración de Base de Datos H2 (En memoria)
spring.datasource.url=jdbc:h2:mem:resenasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola de H2 para ver los datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar los comandos SQL en la consola (útil para debug)
spring.jpa.show-sql=true

# Configuración Circuit Breaker
resilience4j.circuitbreaker.instances.resenaCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.resenaCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.resenaCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.resenaCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.resenaCB.failureRateThreshold=50