name: CI/CD Pipeline - Gamebakes

on:
  push:
    branches:
      - main
      - feature/Luis
      - feature/Esther
      - feature/Franco

jobs:
  analisis-sonarqube:
    name: Análisis de Calidad (SonarCloud)
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build y Analizar con SonarCloud (Servicio Pagos)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd servicios-backend/servicio-pagos
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FrancoM27_FullStack_3

  compilar-y-subir:
    needs: analisis-sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Compilar Microservicios
        run: |
          cd servicios-backend/api-gateway && mvn clean package -DskipTests
          cd ../servicio-usuarios && mvn clean package -DskipTests
          cd ../servicio-resenas && mvn clean package -DskipTests
          cd ../servicio-pedidos && mvn clean package -DskipTests
          cd ../servicio-perfil && mvn clean package -DskipTests
          cd ../servicio-productos && mvn clean package -DskipTests
          cd ../servicio-pagos && mvn clean package -DskipTests

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build y Push de Imágenes Backend
        run: |
          # API Gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-api-gateway:latest ./servicios-backend/api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-api-gateway:latest

          # Usuarios
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-servicio-usuarios:latest ./servicios-backend/servicio-usuarios
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-servicio-usuarios:latest

          # Reseñas
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-servicio-resenas:latest ./servicios-backend/servicio-resenas
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-servicio-resenas:latest

          # Pedidos
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-servicio-pedidos:latest ./servicios-backend/servicio-pedidos
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-servicio-pedidos:latest

          # Perfil
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-servicio-perfil:latest ./servicios-backend/servicio-perfil
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-servicio-perfil:latest

          # Productos
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-servicio-productos:latest ./servicios-backend/servicio-productos
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-servicio-productos:latest

          # Pagos
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-servicio-pagos:latest ./servicios-backend/servicio-pagos
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-servicio-pagos:latest

      - name: Build y Push del Frontend
        run: |
          echo "VITE_API_URL=http://52.1.214.93:9000" > ./gamebakes-web/.env
          
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gb-frontend-react:latest ./gamebakes-web
          docker push ${{ secrets.DOCKER_USERNAME }}/gb-frontend-react:latest